### ISSUE TITLE
Wrong usage example

### ISSUE THREAD

**Issue by EpocDotFr** [RR2DO2/maxminddb-geolite2#3]
The usage example written in the readme is wrong. The Maxmind database isn't closed properly, even by calling `close`. I discovered this issue while using `maxminddb-geolite2` in a Flask project.

The proper usage example should be:

```python
from geolite2 import geolite2

with geolite2 as gl2:
    reader = gl2.reader()

    print(reader.get('8.8.8.8'))
    print(reader.get('125.25.6.5'))
```

**Comment by RR2DO2** [comment]
I just looked into this, when you say the database isn't closed properly, what do you mean exactly? After calling geolite2.close() (as per example) the reader is no longer valid. It raises a ValueError in quick testing.

**Comment by EpocDotFr** [comment]
Closing because I no longer use maxminddb-geolite2, and I'm cleaning all my issues.
